version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hotel_booking_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_booking
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hotel-network
    restart: always

networks:
  hotel-network:
    driver: bridge
